version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener-app
    ports:
      - 8080:8080
    environment:
      SHORTENER_STORAGE_KIND: psql
      SHORTENER_PSQL_HOST: db
      SHORTENER_PSQL_USER: root
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: shortener-postgres
    volumes:
      - shortener-dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: shortener
volumes:
  shortener-dbdata: